- name: Build Scratch GUI
        run: npm run build --workspace=packages/scratch-gui
        env:
          PUBLIC_URL: /${{ github.event.repository.name }}/

      # Add this step to move the files to the root
      - name: Prepare Artifact
        run: cp -r packages/scratch-gui/build/* .

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Now it uploads everything in the root
